# Submoda Development Environment
# Managed by mise (https://mise.jdx.dev)

[settings]
# Use cargo-binstall for faster installations
cargo_binstall = true

[tools]
# Rust pinned for reproducibility
rust = "1.90.0"

# Python for PyO3 bindings and data generation scripts
python = "3.12.11"

# Cargo tools managed by mise, installed with binstall
"cargo:cargo-edit" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:cargo-nextest" = "latest"

[tasks.test]
description = "Run tests"
run = "cargo nextest run --workspace"

[tasks.bench]
description = "Run benchmarks"
run = "cargo bench --workspace"

[tasks.watch]
description = "Watch and rebuild on changes"
run = "cargo watch -x 'nextest run'"

[tasks.fmt]
description = "Format code"
run = "cargo fmt --all"

[tasks.lint]
description = "Run clippy linter"
run = "cargo clippy --workspace --all-targets -- -D warnings -D clippy::pedantic -D clippy::nursery"

[env]
# Set default Rust flags for development
RUST_BACKTRACE = "1"
RUST_LOG = "info"
