# Submoda Development Environment
# Managed by mise (https://mise.jdx.dev)

[settings]
# Use cargo-binstall for faster installations
cargo_binstall = true

[tools]
# Rust pinned for reproducibility
rust = "1.90.0"

# Python for PyO3 bindings and data generation scripts
python = "3.12.12"

# Cargo tools managed by mise, installed with binstall
# Pinned for reproducibility
"cargo:cargo-edit" = "0.13.7"
"cargo:cargo-watch" = "8.5.3"
"cargo:cargo-nextest" = "0.9.105"

[tasks.test]
description = "Run tests"
run = "cargo nextest run --workspace"

[tasks.bench]
description = "Run benchmarks"
run = "cargo bench --workspace"

[tasks.watch]
description = "Watch and rebuild on changes"
run = "cargo watch -x 'nextest run --workspace'"

[tasks.fmt]
description = "Format code"
run = "cargo fmt --all"

[tasks.lint]
description = "Run clippy linter"
run = "cargo clippy --workspace --all-targets --no-deps -- -D warnings -D clippy::pedantic -D clippy::nursery"

[tasks.check]
description = "Check the project for errors"
run = "cargo check --workspace --all-targets"

[env]
# Set default Rust flags for development
RUST_BACKTRACE = "1"
RUST_LOG = "info"
