# Submoda Development Environment
# Managed by mise (https://mise.jdx.dev)

[settings]
# Use cargo-binstall for faster installations
cargo_binstall = true

[tools]
# Rust pinned for reproducibility
rust = "1.90.0"

# Python for PyO3 bindings and data generation scripts
# Using venv for dependency isolation
python = { version = "3.12.12", venv = ".venv" }

# Cargo tools managed by mise, installed with binstall
# Pinned for reproducibility
"cargo:cargo-edit" = "0.13.7"
"cargo:cargo-watch" = "8.5.3"
"cargo:cargo-nextest" = "0.9.105"

[tasks.test]
description = "Run tests"
run = "cargo nextest run --workspace"

[tasks.bench]
description = "Run benchmarks"
run = "cargo bench --workspace"

[tasks.watch]
description = "Watch and rebuild on changes"
run = "cargo watch -c -x 'check --workspace --all-targets' -x 'nextest run --workspace'"

[tasks.fmt]
description = "Format code"
run = "cargo fmt --all"

[tasks.lint]
description = "Run format check and clippy linter"
# Note: -D warnings treats all warnings as errors (strict, suitable for CI)
# For local development, you may run: cargo clippy --workspace --all-targets --no-deps
run = [
    "cargo fmt --all -- --check",
    "cargo clippy --workspace --all-targets --no-deps -- -D warnings -W clippy::pedantic"
]

[tasks.check]
description = "Check the project for errors"
run = "cargo check --workspace --all-targets"

[tasks.install-pip-tools]
description = "Install or upgrade pip and pip-tools"
run = "python -m pip install --upgrade pip pip-tools"

[tasks.pip-install]
description = "Sync Python development dependencies with requirements-dev.txt"
run = "pip-sync requirements-dev.txt"
sources = ["requirements-dev.txt"]
depends = ["install-pip-tools"]

[tasks.pip-compile]
description = "Compile requirements-dev.in to requirements-dev.txt with pip-tools"
run = "pip-compile --generate-hashes --output-file=requirements-dev.txt requirements-dev.in"
sources = ["requirements-dev.in"]
outputs = ["requirements-dev.txt"]
depends = ["install-pip-tools"]

[tasks.setup]
description = "Set up the development environment"
run = "echo 'Development environment ready. Run maturin develop after creating Cargo.toml.'"
depends = [
    "rust",
    "python",
    "cargo:cargo-edit",
    "cargo:cargo-watch",
    "cargo:cargo-nextest",
    "pip-install",
]

[env]
# Set default Rust flags for development
RUST_BACKTRACE = "1"
RUST_LOG = "info"
