# rustfmt configuration for submoda workspace
# https://rust-lang.github.io/rustfmt/

# Edition must match Cargo.toml
edition = "2021"

# Maximum line width
max_width = 100

# Indentation and whitespace
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Function and type formatting
fn_params_layout = "Tall"
fn_single_line = false
where_single_line = false
format_code_in_doc_comments = true
normalize_doc_attributes = true

# Match and control flow
match_arm_blocks = true
match_block_trailing_comma = true
control_brace_style = "AlwaysSameLine"

# Structs and enums
struct_field_align_threshold = 0
use_small_heuristics = "Default"

# Comments and documentation
comment_width = 100
wrap_comments = true
normalize_comments = true

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Blank lines
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1

# Misc formatting
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
condense_wildcard_suffixes = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true

# Error handling
error_on_line_overflow = false
error_on_unformatted = false

# Cargo.toml formatting
unstable_features = false
